---
title: "진행 경과 및 계획"
description: |
  오픈통계 패키지는 현재 진화되고 있으며, 진행된 경과와 2021년내(단기)의 계획을 소개합니다.
site: distill::distill_website
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# BitStat 현황
     
## 개발 버전     
현재 BitStat는 개발 버전으로 0.5.0.9001 버전 번호를 달고 있습니다. 개발 버전인 관계로 CRAN에 등록되어 있지 않고,
github([https://github.com/bit2r/BitStat](https://github.com/bit2r/BitStat){target="_blank"})에만 등록되어 있습니다.

## 프로토타이핑
현재는 프로토타이핑 개발 버전입니다. 그런데 제품(Product) 개발 버전으로 프로젝트가 변경될 경우에는 UI/UX의 골격이 바뀔 수도 있습니다.
현재는 기능적인 프로토타이핑 중으로 UI/UX는 shinydashboard를 채용하고 있습니다.


# 진행 경과
BitStat는 **2021년 9월**부터 개발되 시작한 통계적 데이터 분석 툴의 프로토타이핑입니다.

현재는 데이터 입력/진단을 마무리하고, 데이터 변환 기능을 구현하고 있는 단계입니다.

<br>

* 진행 경과 표

+------------+--------------+---------------+---------------------------+
| 대분류     | 중분류       | 소분류        | 상세 기능                 |
+:===========+:=============+:==============+:==========================+
| 데이터     | 데이터 준비  | 데이터 업로드 | * CSV 파일                |
|            |              |               | * 엑셀 파일               |
|            |              |               | * R 데이터 파일           |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 준비  | 데이터 관리   | * 데이터셋 정보 편집      |
|            |              |               | * 데이터셋 삭제           |
|            |              |               | * 데이터셋 다운로드       |
|            |              |               | * 전체 다운로드           |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 진단  | 진단 개요     | * 데이터 진단 개요        |
|            |              |               | * 데이터 진단 상세        |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 진단  | 변수별 진단   | * 개별 변수별 데이터 진단 |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 진단  | 이상치        | * 이상치 진단 분석        |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 진단  | 보고서 작성   | * pdf 보고서 작성         |
|            |              |               | * web 보고서 작성         |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 변환  | 변수 조작     | * 변수 이름 변경          |
|            |              |               | * 변수 형 변환            |
|            |              |               | * 변수 삭제               |
|            |              |               | * 변수 레벨 순서변경      |
|            |              |               | * 변수 레벨 변경/병합     |
|            |              |               | * 변수 변환               |
|            |              |               | * 변수 비닝               |
+------------+--------------+---------------+---------------------------+


<br>
<br>

# 단기 계획

**2021년 하반기**까지는 **기술통계와 단순선형모형을 구현**할 계획입니다.

<br>

* 진행 계획 표

+------------+--------------+---------------+---------------------------+
| 대분류     | 중분류       | 소분류        | 상세 기능                 |
+:===========+:=============+:==============+:==========================+
| 데이터     | 데이터 변환  | 데이터 정제   | * 결측치 제거/대체        |
|            |              |               | * 이상치 제거/대체        |
|            |              |               | * 중복 관측치 제거        |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 변환  | 데이터 분할   | * Random Simple Sampling  |
|            |              |               | * Bootstrap Sampling      |
|            |              |               | * Holdout Sampling        |
+------------+--------------+---------------+---------------------------+
| 기술통계   | EDA          | 단변량        | * 통계량                  |
|            |              |               | * 시각화                  |
+------------+--------------+---------------+---------------------------+
| 기술통계   | EDA          | 이변량        | * 통계량                  |
|            |              |               | * 시각화                  |
+------------+--------------+---------------+---------------------------+
| 기술통계   | EDA          | 다변량        | * 통계량                  |
|            |              |               | * 시각화                  |
+------------+--------------+---------------+---------------------------+
| 회귀분석   | 단순선형모형 | 모델 적합     | * 변수선택                |
|            |              |               | * 모델 적합               |
+------------+--------------+---------------+---------------------------+
| 회귀분석   | 단순선형모형 | 모델 진단     | * 모델 진단               |
+------------+--------------+---------------+---------------------------+
| 회귀분석   | 단순선형모형 | 예측          | * 예측                    |
+------------+--------------+---------------+---------------------------+

